<?php

namespace MauticPlugin\MauticLdapAuthBundle\Security\Provider;

use Mautic\UserBundle\Security\Provider\UserProvider;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;

/**
 * @method UserInterface loadUserByIdentifier(string $identifier)
 */
class LdapUserProvider extends UserProvider implements UserProviderInterface
{

    public function refreshUser(UserInterface $user)
    {
        return parent::refreshUser($user);
        // TODO: Implement refreshUser() method.
    }

    public function supportsClass(string $class): bool
    {
        return parent::supportsClass($class);
        // TODO: Implement supportsClass() method.
    }

    public function loadUserByUsername($username): UserInterface|\Mautic\UserBundle\Entity\User
    {
        return parent::loadUserByUsername($username); // TODO: Change the autogenerated stub
    }

}